version: "3.9"

services:
  web:
    build: .
    container_name: taqueria_django

    working_dir: /app

    volumes:
      - ./Proyecto_GP4:/app

    ports:
      - "8000:8000"

    command: python manage.py runserver 0.0.0.0:8000